logsBucket: 'gs://my-project-logs'

steps:
  # Step 1: Build and push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/amplified-asset-426508-e7/my-apache-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/amplified-asset-426508-e7/my-apache-app']

  # Step 2: Fetch credentials for GKE cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials my-gke-cluster --zone=us-central1-a --project=amplified-asset-426508-e7

  # Step 3: Deploy application using kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        kubectl apply -f deployment.yaml --record=true

images:
  - 'gcr.io/amplified-asset-426508-e7/my-apache-app'
