steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/amplified-asset-426508-e7/my-apache-app', '.']
    dir: '.'

  # Step 2: Push Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/amplified-asset-426508-e7/my-apache-app']

  # Step 3: Fetch credentials for GKE cluster (my-gke-cluster)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'my-gke-cluster', '--zone=us-central1-a', '--project=amplified-asset-426508-e7']

  # Step 4: Deploy application using kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment.yaml', '--record=true']

images:
  - 'gcr.io/amplified-asset-426508-e7/my-apache-app'
