steps:
  # Step 1: Build and push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/amplified-asset-426508-e7/my-apache-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/amplified-asset-426508-e7/my-apache-app']

  # Step 2: Set KUBECONFIG and deploy using kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$KUBE_CONFIG_DATA" > /workspace/.kube/config
        kubectl apply -f deployment.yaml --record=true

images:
  - 'gcr.io/amplified-asset-426508-e7/my-apache-app'
