logsBucket: 'gs://my-logs-bucket'
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-apache-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-apache-app']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'my-gke-cluster', '--zone', 'us-central1-a', '--project', '$PROJECT_ID']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['create', 'deployment', 'my-apache-app', '--image=gcr.io/$PROJECT_ID/my-apache-app', '--port=80']

options:
  logs_bucket: 'gs://my-logs-bucket'
  serviceAccount: '333995508011-compute@developer.gserviceaccount.com'

substitutions:
  _PROJECT_ID: amplified-asset-426508-e7

images:
  - gcr.io/$PROJECT_ID/my-apache-app
