logsBucket: 'gs://my-project-logs'

env:
  - CLOUDSDK_COMPUTE_REGION=us-central1
  - CLOUDSDK_COMPUTE_ZONE=us-central1-a
  - CLOUDSDK_CONTAINER_CLUSTER=my-gke-cluster

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/amplified-asset-426508-e7/my-apache-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/amplified-asset-426508-e7/my-apache-app']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'my-gke-cluster', '--zone', 'us-central1-a', '--project', 'amplified-asset-426508-e7']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['config', 'set', 'container/cluster', 'my-gke-cluster']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['config', 'set', 'compute/zone', 'us-central1-a']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['create', 'deployment', 'my-apache-app', '--image=gcr.io/amplified-asset-426508-e7/my-apache-app', '--port=80']

images:
  - gcr.io/amplified-asset-426508-e7/my-apache-app
