steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-apache-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-apache-app']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'my-gke-cluster', '--zone', 'us-central1-a', '--project', '$PROJECT_ID']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['create', 'deployment', 'my-apache-app', '--image=gcr.io/$PROJECT_ID/my-apache-app', '--port=80']

substitutions:
  _PROJECT_ID: $PROJECT_ID

options:
  machineType: 'e2-medium'
  diskSizeGb: 50

images:
  - gcr.io/$PROJECT_ID/my-apache-app
