logsBucket: 'gs://my-project-logs'

steps:
  # Step 1: Authenticate with GCP
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['auth', 'login']

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-apache-app', '.']
    dir: '.'

  # Step 3: Push Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-apache-app']

  # Step 4: Fetch credentials for GKE cluster (my-gke-cluster)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'my-gke-cluster', '--zone=us-central1-a', '--project=$PROJECT_ID']

  # Step 5: Deploy application using kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment.yaml', '--record=true']

images:
  - 'gcr.io/$PROJECT_ID/my-apache-app'

substitutions:
  _PROJECT_ID: amplified-asset-426508-e7
