steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/amplified-asset-426508-e7/my-apache-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/amplified-asset-426508-e7/my-apache-app']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'my-gke-cluster', '--zone', 'us-central1-a', '--project', 'amplified-asset-426508-e7']
  - name: 'gcr.io/cloud-builders/terraform'
    args: ['init']
  - name: 'gcr.io/cloud-builders/terraform'
    args: ['apply', '-auto-approve']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['create', 'deployment', 'my-apache-app', '--image=gcr.io/amplified-asset-426508-e7/my-apache-app', '--port=80']

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/amplified-asset-426508-e7/my-apache-app'
