apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-apache-app
  template:
    metadata:
      labels:
        app: my-apache-app
    spec:
      containers:
      - name: my-apache-app
        image: gcr.io/amplified-asset-426508-e7/my-apache-app
